
name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['linux-x64', 'win-x64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.101 # Change this to the desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish for ${{ matrix.os }}
      run: dotnet publish -r ${{ matrix.os }} -p:IncludeNativeLibrariesForSelfExtract=true -c Release AntlrCSharp/

    - name: Set up Git
      run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./AntlrCSharp/bin/Release/net8.0/${{ matrix.os }}/publish/grund
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Grund Release ${{ github.sha }} - $GITHUB_REF_NAME
        body: |
          Release notes for version ${{ github.sha }} - ${{ matrix.os }}.
          Auto Generated Stuff for Git Actions!
